# This workflow will build and push an application to a Azure Kubernetes Service (AKS) cluster
name: Build and deploy an app to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@master
        with:
          repository: SSPJ/verbose-octo-broccoli
          path: infrastructure
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Ls after CD
        run: |
          cd main
          ls
          pwd
      - name: Ls without CD
        run: |
          ls
          pwd
